### ISSUE TITLE
List the types of punishments issue.

### ISSUE THREAD

**Issue by salasan1** [mathhulk/ab-web-addon#12] opened 2017-07-23 08:47 UTC
`$types = array('kaikki','porttikielto','temp_ban','mute','temp_mute','warning','temp_warning','kick');`
and it looks like [this](http://i.imgur.com/mRVuM6E.png) so problem is if i change that ban to porttikielto it will shows that 0 player is banned so what is problem?

**Comment by mathhulk** [comment] 2017-07-23 23:23
The problem is that AdvancedBan does not support multiple languages for punishments.

**Comment by salasan1** [comment] 2017-07-25 07:10
so you cant do anythink to that problem no methods?

**Comment by mathhulk** [comment] 2017-07-26 03:09
Will be fixed in the next update when I add a language file.

**Comment by mathhulk** [comment] 2017-07-26 03:09
Going to keep this open as a reminder.

**Closed** 2017-07-26 19:59 UTC
