### ISSUE TITLE
No view

### ISSUE THREAD

**Issue by CCCCarsten** [mathhulk/ab-web-addon#5] opened 2017-04-28 14:30 UTC
Hi!

I have connection to my SQL database. You can see it by the following picture. But I don't see the punished players... what is going wrong? I am sorry but it is a pain for me to understand php and so on. 

![tabelle](https://cloud.githubusercontent.com/assets/18105655/25533157/f3ccf42e-2c2f-11e7-92a1-0a6d4f2ec68c.jpg)

Thank you in advance for this addon.

Ciao, Carsten

**Comment by mathhulk** [comment] 2017-04-29 01:57
This seems to be a problem for a lot of users... I have absolutely no idea what the problem is. Have you tried updating your PHP version?

**Comment by CCCCarsten** [comment] 2017-04-29 10:48
Hi mathhulk, I have no chance to update PHP. because I would not know what I have to do :). The web content is hosted by a friend and I will ask him for the php version.

**Comment by CCCCarsten** [comment] 2017-04-29 22:44
Hi mathhulk, the php-version I actually use is PHP 5.4.45. What can I do to help you?

**Comment by mathhulk** [comment] 2017-05-01 03:09
I honestly have no idea why it isn't working. Are you using the latest version?

**Comment by CCCCarsten** [comment] 2017-05-02 19:39
?? I have written 5.5.38-See above :)

**Comment by mathhulk** [comment] 2017-05-03 17:15
The latest version of PHP is 7.x, but I am asking if you are using the latest version of the AdvancedBan Web Addon.

**Comment by CCCCarsten** [comment] 2017-05-03 18:08
Yes, I do.

**Comment by mathhulk** [comment] 2017-07-10 03:05
This should be fixed in the latest version. If not, please create another issue.

**Closed by mathhulk** 2017-07-10 03:05 UTC
